name: Docker Image CI

on: 
  release:
    types: published

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare release info
      id: info
      run: |
        echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\/}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/rust-centos7-openssl-libxml2-xmlsec1-builder:${{steps.info.outputs.TAG}} --tag ${{secrets.DOCKER_USER}}/rust-centos7-openssl-libxml2-xmlsec1-builder:latest
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Docker push
      run: |
        docker push ${{secrets.DOCKER_USER}}/rust-centos7-openssl-libxml2-xmlsec1-builder:${{steps.info.outputs.TAG}}
        docker push ${{secrets.DOCKER_USER}}/rust-centos7-openssl-libxml2-xmlsec1-builder:latest
